# Generated by Django 3.2.5 on 2023-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=100, verbose_name='電子郵件')),
                ('subject', models.CharField(max_length=100, verbose_name='主旨')),
                ('message', models.TextField(max_length=500, verbose_name='訊息')),
            ],
            options={
                'verbose_name': '訪客留言',
                'verbose_name_plural': '訪客留言',
                'ordering': ['-id'],
            },
        ),
    ]
