# Generated by Django 3.2.5 on 2023-05-16 06:31

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_localesetting_translatesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='繁體中文')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='英文')),
            ],
            options={
                'verbose_name': '欄位多語系',
                'verbose_name_plural': '欄位多語系',
            },
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='slideimage_name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='image')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_slideimage_set', to='core.setting')),
            ],
            options={
                'verbose_name': 'Slideimage',
                'verbose_name_plural': 'Slideimage',
                'ordering': ['order'],
            },
        ),
    ]
