# Generated by Django 3.2.5 on 2023-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_locale_slideimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='電話'),
        ),
    ]
