# Generated by Django 3.2.5 on 2023-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_setting_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='EMAIL'),
        ),
    ]
