# Generated by Django 3.2.5 on 2023-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230520_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Product Description En'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Name En'),
        ),
    ]
